"""regresando el campo contraseña

Revision ID: 70374efc3286
Revises: e853dbfac724
Create Date: 2025-04-17 21:09:49.660543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70374efc3286'
down_revision = 'e853dbfac724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', sa.String(length=200), nullable=False))
        batch_op.drop_column('_contraseña')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_contraseña', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('contraseña')

    # ### end Alembic commands ###
